### ISSUE TITLE
[feature] Instances Page and Dialog

### ISSUE THREAD

**Issue by ivicac** [bytechefhq/bytechef#227]
As a User
I want to create/edit/delete project instances
So that I can activate the same workflows with different configurations and connections (prod, uat, ty).

### Acceptance Criteria
A user is able to create update and delete project instances. 

### Subtasks

- [x] Extend the current Connection dialog and add vertical steps on the left side.
- [x] Basic step - [Mockup](https://balsamiq.cloud/spslzug/ph7qmda/r79F9)
- [x] Add Workflows step - [Mockup](https://balsamiq.cloud/spslzug/ph7qmda/r994C)
    - [x] Configuration tab - [Mockup](https://balsamiq.cloud/spslzug/ph7qmda/r5E48)
        - [x] There can be three types of configuration properties: string, number, and boolean (treat at the frontend `string` as `StringProperty`, `number` as `NumberProperty`, and `boolean` as `BooleanProperty`).
    - [x] Connections tab - [Mockup](https://balsamiq.cloud/spslzug/ph7qmda/r9489)

### Technical details
Endpoint for create/update: `/api/automation/project-instances`

### Known bugs
- [x] https://share.cleanshot.com/H77PcZ6W
- [x] https://share.cleanshot.com/DlBy9Kjk
- [x] https://share.cleanshot.com/FhnX8Nry
- [x] https://share.cleanshot.com/1m9VpKXk
- [x] https://share.cleanshot.com/KPLt7JV8
- [x] https://share.cleanshot.com/p0jbX50b
- [x] https://share.cleanshot.com/xdPpW78J
- [x] https://share.cleanshot.com/Sk6C7jv4
- [x] After inputting data and clicking Next, going back to the Basic tab, the `FilterableSelect` has no selected project
- [x] When submitting data, empty tags should be sent as an empty array `[]`, not an array with an empty object `[{}]`
- [x] The `Next` button should be disabled if a project has not been selected
- [x] In the Basic step, the Instance Name input is automatically focused, but we want the Project Select to be automatically focused instead
- [x] When done typing in the Instance Name input we need to instantly update the disabled state of the Next button. Currently it gets updated when focus is changed.
