### ISSUE TITLE
[feature] Workflow Executions Details Dialog

### ISSUE THREAD

**Issue by ivicac** [bytechefhq/bytechef#285]
### Description
Details of each Project Execution so that I can check the duration, input, and output of each executed task.

### Mockup 
https://balsamiq.cloud/spslzug/ph7qmda/rE55A

### Milestones
- [x] Static UI that gets shown when a table row is clicked
- [x] Connect the static UI to API endpoints
- [x] Add read-only workflow (requires saving current workflow in the workflow definition)

### Improvements
- [x] Remove `outputDummyData` and handle the UI in case of no output
- [x] Change background colors to match Balsamiq
