### ISSUE TITLE
[feature] Component configuration during workflow building

### ISSUE THREAD

**Issue by ivicac** [bytechefhq/bytechef#303]
### Description

As a User I want to see a component configuration panel (for each component used for building a workflow So that I can properly configure them.

### Acceptance Criteria
1. Opens on the right side of the screen.
2. The workflow editor area is still clickable and movable while the panel is open.
3. Mockup - https://balsamiq.cloud/spslzug/ph7qmda/r6139

### Milestones
- [x] `Description` tab
- [ ] Properties tab (the `Properties` component is base) by `controlType`:
    - [x] `TEXT`
    - [x] `INTEGER` 
    - [x] `PASSWORD`
    - [x] `SELECT`
    - [x] `CODE_EDITOR`
    - [x] `NUMBER`
    - [x] `DATE`
    - [x] `TIME`
    - [x] `DATE_TIME`
    - [x] `EMAIL`
    - [x] `PHONE`
    - [x] `URL`
    - [x] `MULTI_SELECT`
    - [x] `TEXT_AREA`
    - [ ] `ARRAY_BUILDER`
    - [ ] `OBJECT_BUILDER`
- [x] Properties by `type`:
    - [x] `ARRAY`
    - [x] `BOOLEAN`
    - [x] `OBJECT`
- [x] `Connection` tab
  - [x] Invokes a ConnectionDialog with a prepopulated Component field that is disabled
  - [x] The note should be dismissable and the state should be stored in the cache
- [x] `Output` tab
- [ ] Saving data to Workflow Definition

### Technical details
- Endpoint for a component with a basic list of actions: `/component-definitions/{componentName}/{componentVersion}`
- Endpoint for a list of connections: `/connections?componentNames={componentName}`

### Known bugs
- [x] Action select is buggy
    - [x] [Jira](https://prnt.sc/2HDGMCiB8I2R)
    - [x] [Pipedrive](https://prnt.sc/o49v1umCeEdD)
    - [x] [Mailchimp](https://share.cleanshot.com/qcmnJnJs)
- [ ] Deleting a node doesn't remove it from the `previousComponents (useGetComponentDefinitionsQuery)` data
