### ISSUE TITLE
[feature]: Basic error handling on backend and frontend

### ISSUE THREAD

**Issue by ivicac** [bytechefhq/bytechef#370]
### Description
Show system/application errors in Admin UI that happen on the backend side, so that the user can act accordingly by either correcting my operations upon app errors or reporting system errors.

### Tasks
- [ ]  Implement centralized error handling on the backend: https://www.baeldung.com/problem-spring-web, check as an example: https://github.com/jhipster/jhipster-sample-app-gradle/blob/main/src/main/java/io/github/jhipster/sample/web/rest/errors/ExceptionTranslator.java
- [ ] Implement centralized error handling on the frontend
- [ ] Standardize and implement form error handling (`react-hook-form` `errors`)
    - [ ] `onBlur` for empty fields that are `required`
    - [ ] `{rules: {required: true}}` should behave like the `required` prop

Acceptance Criteria
TODO
