### ISSUE TITLE
[feature] DataPills panel for picking outputs from the previous steps in the Workflow Editor

### ISSUE THREAD

**Issue by ivicac** [bytechefhq/bytechef#373]
### Description
As a Workflow Developer
I want to see output values of each previous Workflow Step (output values from components used in Steps)
So that I can choose input values for the component used in the current Workflow Step I am building.

### Technical Notes
- [Balsamiq Mockup](https://balsamiq.cloud/spslzug/ph7qmda/r4BB0)
- Data Pills represent Output data of each previous component's currently selected Action

### Milestones
- [x] Static Dialog component that gets shown to the left of the NodeDetailsDialog after an InputProperty has been focused
- [x] Gain access to the workflow nodes
- [x] Create a new endpoint that accepts multiple component names and action names, and returns a list of action definitions
- [x] Consume the output schemas of those action definitions an `Accordion` component
- [x] Clicking on a datapill adds it to the focused input
- [x] Add a filter input on top of the accordions, to filter the data pills

### TODO
- [x] `previousComponents` should take into account the currently selected/open component - currently it is always showing all components except the last one
- [x] Add the ability to scroll big accordion contents
- [x] Add the ability to delete the data pills with backspace
- [x] Persist the focus state of the focused input to indicate where the datapill will be added
- [x] Handle same components (e.g. `httpClient` and `httpClient-1`)
- [x] Add MentionsInput to other field types
- [x] Add icon representing the type, like other inputs
- [x] Add description tooltip to the MentionsInput label
- [x] Make the description tooltip a fixed width
- [ ] Handle `DYNAMIC_PROPERTIES` type (Airtable) - Will be fixed by [265](https://github.com/bytechefhq/bytechef/issues/265)

### Special cases
- [x] Figure out how to visualize an OBJECT

### DataPillPanel Bugs
- [x] [Duplicate actionData entry](https://prnt.sc/_SvSJITwLO-M)
    - Steps to reproduce: Add `Mailchimp` and click on it, add `Airtable` and click on it, change `Airtable` action to `Custom Action`
- [x] [getComponentDefinitions](https://github.com/bytechefhq/bytechef/blob/master/client/src/middleware/core/workflow/configuration/apis/ComponentDefinitionsApi.ts#L161-L164) endpoint is alphabetically sorting the array of strings sent via the include parameter
- [x] [Pipedrive data property is not displayed as an array](https://prnt.sc/mXZDHB2TqXZI)
- [x] Airtable sub-properties are not being displayed
- [x] First render of Properties tab, the `MentionsInput` isn't being rendered (`dataPills` prop is empty)
- [x] Positioning of the mention dropdown is bugged
- [x] When clicking on arbitrary components in the workflow, the properties in DPP get assigned to components they don't belong to
- [x] When scrolling, the `MentionsInput` placeholder moves away from the input
- [x] When a `MentionsInput` is focused, and the DPP is opened, the focus changes away from the input
- [x] `Cannot read properties of undefined (reading 'delta')`
    - Add Airtable, AWS-S3 and Pipedrive to workflow
    - Change Pipedrive action to "Add a deal"
    - Click on Airtable, AWS-S3 and then Pipedrive
- [x] Don't render Select inputs that have no options to be selected (Airtable)
- [x] [Show previous components in DPP even if they haven't been previously clicked](https://share.cleanshot.com/8mJ6mySn)
- [x] [Add the expression input toggle for all input types (select)](https://share.cleanshot.com/0CRTT4Mw)
- [x] [DataPillPanel Header tooltip should be smaller](https://share.cleanshot.com/ksZFhngM)
- [x] [The entire datapill isn't round when inside the input](https://share.cleanshot.com/VFVMCCxb)
- [x] [All basic input types except string should allow only 1 datapill](https://share.cleanshot.com/2bb3Z44n)
- [x] When clicking on a datapill to add it to the input, the icon is undefined
- [x] https://share.cleanshot.com/DgQSFnzB - @ivicac 
- [x] https://files.slack.com/files-tmb/T09FV82B0-F061Y9P51V3-6457d0f7bf/image_720.png - @ivicac 
- [x] Fix datapill panel layout - @ivicac 
- [x] [When the button to switch to mention input is clicked open the DataPillPanel and focus the input](https://share.cleanshot.com/VrnsMbZJ)
- [x] [Changing between components sets the input type to standard input](https://share.cleanshot.com/y84vNKRl)
- [x] [String type input does not need to have the input type change button](https://share.cleanshot.com/x3341pdt)
- [x] [The required indicator is missing on mention inputs](https://share.cleanshot.com/F2Y6qqr2)
- [x] [When a node is added in-between existing ones while NodeDetailsPanel is open, the DataPillPanel isn't updated with the new component](https://share.cleanshot.com/L92shRM8)
- [x] [Reduce the usage of `useEffect`](https://share.cleanshot.com/6xmLXj5T)
- [x] When adding an inbetween node, the DPP gets rerendered twice
- [x] A `0` is shown under some properties
- [x] [Add a root for the component representing the entire object](https://share.cleanshot.com/C6fjsFph)
- [x] [When 2 of the same components are in the workflow, only one is shown in DPP](https://prnt.sc/Qdm2g-M9UK9Z)

### NodeDetailsPanel bugs
- [x] When multiples of the same components are present, the action gets set for all of them
- [x] [Airtable Properties tab shows "dynamic properties" when components are changed](https://share.cleanshot.com/8b4q6dmJ) - cannot reproduce
- [x] [Add a more detailed path to the datapill inside the input](https://share.cleanshot.com/lyq4SWtH)
- [x] [Missing data under Pipedrive `data` property - output](https://share.cleanshot.com/JZ7P1r93)
- [x] [getBoundingClientRect null error when focusing - focus not working properly](https://share.cleanshot.com/J30CjNK1)
- [x] [Regular property input retains the value of the mention input](https://share.cleanshot.com/LbzjWJM2)
- [x] https://share.cleanshot.com/jnPLlkRr
- [x] Currently open tab isn't preserved when changing actions
- [x] [When there are no components in the workflow, hide the panel](https://share.cleanshot.com/LhcYqcwF)
- [x] Unbroken lines of text extend the width of the MentionInput to exceed the container width
- [x] [httpClient has no output data but data pill UI is still shown](https://shottr.cc/s/1PGa/SCR-20231121-jlw.png)
- [x] [Data Mapper has an empty property](https://shottr.cc/s/1pJI/SCR-20231123-da4.png)
- [x] [The DPP closes when browser tab loses focus](https://share.cleanshot.com/RRCS45CD)
- [x] [Input component moves when clicking input type switch button](https://share.cleanshot.com/tW6R9tHf)
- [x] [fileEntry should have a specific implementation](https://share.cleanshot.com/Q4wmcrZY)
- [x] Remove the input type switch button and implement datapill/value deletion if the other is added
- [x] [Tabs under a specific Petstore action don't work properly](https://shottr.cc/s/1ZCr/SCR-20231128-jqi.png)
- [x] When `XLSX File` is added, there is no output defined, even though the output schema is defined as `array`
- [x] The datapills offered in the popover need to have more specific path
- [x] [When one field is of type `DYNAMIC_PROPERTIES`, other properties are not shown](https://share.cleanshot.com/fRDXNS83)
- [x] integer property -> mogu upisat slova, ali ako prvo upisem znamenku onda ne dopusta ostale znakove
- [x] number property -> ne dopusta unos decimalnih. Isto kao kod integera, ako prvo upisem znamenku ne dopusta druge znakove
- [x] postaviti defaultValue property-ja u sucelju, as i bez opcija
- [x] option("name", "value", "description") - descripton se ne prikazuje u sucelju
- [x] https://share.cleanshot.com/lhhhrDfz
- [x] https://share.cleanshot.com/1KZNwSGT

### Workflow Editor Bugs
- [x] [When adding 2 of the same component and clicking on the 2nd, the app breaks](https://share.cleanshot.com/VjTBCZ8d)
- [x] [Make the dropzone bigger](https://share.cleanshot.com/cXGZtCCv)
- [x] [`workflowAlias `should start from 1](https://share.cleanshot.com/TXL1BZS7)
- [x] [When all components are deleted, a `multiple roots` error occurs](https://share.cleanshot.com/p8x8vtkr)
- [x] [There shouldn't be a situation where 2 `+` nodes are present one after the other](https://share.cleanshot.com/dpwYC6xh)
- [x] [When quickly switching between ContextMenu tabs, the UI flickers](https://share.cleanshot.com/PKc8vL71)
- [x] When adding components through the sidepanel, the `componentAction` isn't defined so datapills don't work
- [x] [Console error when clicking on Manual Trigger followed by clicking a node](https://share.cleanshot.com/2Yv2qqMg)
- [x] [Network requests are being executed when Manual Trigger is hovered](https://share.cleanshot.com/Zz5WkxvR)
- [x] [Workflow nodes are not tied to a particular workflow but to the UI](https://share.cleanshot.com/s5fS7K8W)
- [x] `WorkflowNodesTabs` are not the same in `PopoverMenu` and `Sidebar`
- [x] [Clicking on nodes is inconsistent when the NodesSidebar is used](https://share.cleanshot.com/Dnx4bxKk)
- [x] [When changing an action of a previous component, the component is missing from the DataPillPanel](https://share.cleanshot.com/7MXwDb6L)

### Future
- [ ] Add the ability to drag-and-drop output properties from the `AccordionItem` to the `InputProperty` - https://share.cleanshot.com/85RJfCcc
