### ISSUE TITLE
[feature] Workflows of each Project Instance visible in the list of Project Instances

### ISSUE THREAD

**Issue by ivicac** [bytechefhq/bytechef#374]
### Description
As a User 
I want to see for Project Instance the list of related workflows in the list of Project Instances
So that I can see workflows belonging to each instance and also to be able to enable/disable each individual workflow

### Technical Notes
- [Balsmiq Mockup](https://balsamiq.cloud/spslzug/ph7qmda/r2EBD/b56FA)

### Milestones

- [x] Modify the component structure to match the mockup
    - Project name should be a heading and under it should be an `Accordion` of instances belonging to that project
    - Each instance is an `AccordionItem` and must have an icon representing its current state (down/right arrow)
    - When an instance is opened, we need to show workflows that belong to it
    - Simplify the current representation of an instance to look like an accordion and to look as close to the mockup as possible
- [x] Add navigation when a workflow is clicked, leading us to its page
- [x] Add the ability to toggle on/off instances and individual workflows

### Advanced
- [x] Add icons to the workflow list item representing the components used inside it 

### Bugs
- [x] Filtering doesnt work properly, all instances are being shown regardless of the filtering state
- [x] @ivicac [Potential backend bug](http://127.0.0.1:9555/swagger-ui/index.html#/project-instances/getProjectInstances)

### Instances
- [x] Workflows should have `lastModifiedDate` of the "project instance workflow"
- [x] Workflows should have a dropdown with the Edit option
    - [x] Same information as that workflow (inputs + connections) has inside the Create Instance Dialog
