### ISSUE TITLE
[feature] Workflows of each Project should be visible in the list of Projects

### ISSUE THREAD

**Issue by ivicac** [bytechefhq/bytechef#375]
Change the way we display Projects to feature an accordion that lists the Workflows that belong to that project.
[Balsmiq Mockup](https://balsamiq.cloud/spslzug/ph7qmda/rAF55)

### Technical Notes
- [x] Wrap the `ProjectListItem` component in a radix-accordion (`Accordion`) component
- [x] Create a new `ProjectWorkflowList` component and render it when the `Accordion` is open
- [x] Each Workflow should be clickable and navigate to the matching workflow page

### TODO

- [ ] Add a "New Workflow" button that's aligned with the "Workflows" heading
- [ ] Add the `lastModifiedDate` on the right side of the workflow list item
